# This file contains special global strings that don't need to be translated.
# The contents of this bundle are merged into Core.bundle, and otherwise act as normal translated strings.

# sector.NAME.credit = CREDITS